# Generated by Django 2.2.16 on 2022-01-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220112_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter group name', max_length=200, verbose_name='Group title')),
                ('slug', models.SlugField(help_text='short label', unique=True, verbose_name='slug')),
                ('description', models.TextField(help_text='Enter group description', verbose_name='description')),
            ],
        ),
    ]
